#ifndef DISPLAYINFO_GLOBAL_H
#define DISPLAYINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYINFO_LIBRARY)
#  define DISPLAYINFOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYINFOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYINFO_GLOBAL_H
